python main.py \
--mode test \
--load_checkpoint 1800 \
--lr 4e-6 \
--total_epochs 15 \
--total_steps 1500 \
--eval_steps 300 \
--save_steps 300 \
--batch_size 1 \
--weight_decay 1e-3 \
--model "roberta-hg" \
--dataset "annomi-preprocessed" \
--erc_temperature 0.5 \
--hg_dim 512 \
--exclude_others 0 \
--erc_mixed 1