python main.py \
--lr 4e-6 \
--total_epochs 8 \
--total_steps 3000 \
--eval_steps 200 \
--save_steps 200 \
--batch_size 16 \
--weight_decay 1e-3 \
--model "roberta-hg" \
--dataset "esconv-preprocessed" \
--erc_temperature 0.5 \
--hg_dim 512 \
--exclude_others 0 \
--erc_mixed 1